"""Loss functions: PMI, entropy guard, redundancy reduction, variance guard, PD."""

import torch
import torch.nn.functional as F
from typing import List, Optional

EPS = 1e-8


# ─────────────────────────────────────────────────────────────────────────────
# Module 1 + 2: Cross-view Prototype MI  +  Marginal Entropy Guard
# ─────────────────────────────────────────────────────────────────────────────

def pmi_loss(q_a: torch.Tensor, q_b: torch.Tensor) -> torch.Tensor:
    """Negative MI between cluster assignments of two paired views.

    Args:
        q_a, q_b: (B, K) soft assignments for paired samples.
    Returns:
        Scalar loss (minimize to maximize MI).
    """
    B, K = q_a.shape
    # Joint distribution P(j, k) = (1/B) Σ_i q_a[i,j] * q_b[i,k]
    P = torch.einsum("bi,bj->ij", q_a, q_b) / B + EPS  # (K, K)
    P = P / P.sum()

    # Stop-gradient on marginals (only differentiate through joint)
    with torch.no_grad():
        P_a = P.sum(dim=1, keepdim=True)   # (K, 1)
        P_b = P.sum(dim=0, keepdim=True)   # (1, K)

    mi = (P * (torch.log(P) - torch.log(P_a) - torch.log(P_b))).sum()
    return -mi  # minimize negative MI


def entropy_loss(q: torch.Tensor) -> torch.Tensor:
    """Negative marginal entropy of soft assignments (prevent cluster collapse).

    Args:
        q: (N_v, K) soft assignments for available samples in one view.
    Returns:
        Scalar loss (minimize to maximize marginal entropy).
    """
    q_bar = q.mean(dim=0) + EPS           # (K,) average cluster usage
    return (q_bar * q_bar.log()).sum()     # = -H(q_bar); minimize → maximize H


# ─────────────────────────────────────────────────────────────────────────────
# Module 3: Feature-Level Redundancy Reduction
# ─────────────────────────────────────────────────────────────────────────────

def rr_loss(
    h_a: torch.Tensor,
    h_b: torch.Tensor,
    lambda_off: float = 0.005,
) -> torch.Tensor:
    """Barlow-Twins-style redundancy reduction for cross-view representations.

    Args:
        h_a, h_b: (B, d) latent representations for paired samples.
        lambda_off: penalty weight for off-diagonal correlation terms.
    Returns:
        Scalar loss.
    """
    B, d = h_a.shape
    # Batch-normalize each feature dimension
    h_a = (h_a - h_a.mean(0)) / (h_a.std(0) + EPS)
    h_b = (h_b - h_b.mean(0)) / (h_b.std(0) + EPS)

    C = h_a.T @ h_b / B                           # (d, d) cross-correlation
    I = torch.eye(d, device=h_a.device)
    on_diag = (C.diagonal() - 1).pow(2).sum()     # diagonal → 1
    off_diag = ((1 - I) * C).pow(2).sum()          # off-diagonal → 0
    return on_diag + lambda_off * off_diag


def var_loss(h: torch.Tensor, gamma: float = 1.0) -> torch.Tensor:
    """VICReg variance guard: penalize low-variance feature dimensions.

    Args:
        h: (N_v, d) representations for available samples in one view.
        gamma: target minimum std (typically 1.0).
    Returns:
        Scalar loss.
    """
    std = h.std(dim=0)                      # (d,) per-feature std
    return F.relu(gamma - std).mean()


# ─────────────────────────────────────────────────────────────────────────────
# Module 4: Prototype-Guided Distillation
# ─────────────────────────────────────────────────────────────────────────────

def compute_prototypes(
    H: List[torch.Tensor],
    Q: List[torch.Tensor],
    mask: torch.Tensor,
    n_views: int,
    n_clusters: int,
    d_z: int,
) -> List[torch.Tensor]:
    """Soft-weighted per-view prototypes from all available samples.

    μ_k^v = Σ_i q_{i,k}^v · h_i^v / Σ_i q_{i,k}^v

    Args:
        H: list of (B, d_z) latent representations per view.
        Q: list of (B, K) soft assignments per view.
        mask: (B, V) binary availability mask.
    Returns:
        List of (K, d_z) prototype tensors per view.
    """
    device = H[0].device
    prototypes = []
    for v in range(n_views):
        avail = mask[:, v] > 0
        if avail.sum() < 1:
            prototypes.append(torch.zeros(n_clusters, d_z, device=device))
            continue
        q_v = Q[v][avail]                                   # (N_v, K)
        h_v = H[v][avail]                                   # (N_v, d_z)
        w = q_v.T                                           # (K, N_v)
        w = w / (w.sum(dim=1, keepdim=True) + EPS)
        prototypes.append(w @ h_v)                         # (K, d_z)
    return prototypes


def pd_loss(
    model,
    H: List[torch.Tensor],
    Q: List[torch.Tensor],
    mask: torch.Tensor,
    prototypes: List[torch.Tensor],
    tau_d: float,
    delta: float,
    n_views: int,
    n_clusters: int,
) -> torch.Tensor:
    """Prototype-guided distillation for samples missing some views.

    For sample i observed in view v but not in view u, a pseudo assignment
    q̃_i^u is generated by mapping h_i^v through φ_{v→u} and comparing to
    prototype centroids of view u.  A confidence-weighted KL divergence
    encourages q_i^v to agree with the pseudo q̃_i^u.

    Args:
        model: ProtoMI instance (used for map_proto).
        prototypes: list of (K, d_z) per view.
        tau_d: distillation temperature.
        delta: current ramp-up weight.
    Returns:
        Scalar loss (already scaled by delta).
    """
    if delta == 0.0:
        return torch.zeros(1, device=H[0].device, requires_grad=False).squeeze()

    total = torch.zeros(1, device=H[0].device).squeeze()
    count = 0

    for v in range(n_views):
        for u in range(n_views):
            if u == v:
                continue
            # Samples observed in v but missing in u
            sel = (mask[:, v] > 0) & (mask[:, u] == 0)
            if sel.sum() == 0:
                continue

            idx = sel.nonzero(as_tuple=True)[0]
            h_sv = H[v][idx]                               # (|S|, d_z)
            q_sv = Q[v][idx]                               # (|S|, K)
            proto_u = prototypes[u]                        # (K, d_z)

            # Pseudo assignment via cosine similarity to prototypes
            # Normalising both sides makes tau_d a consistent temperature
            # regardless of representation scale.
            h_mapped  = F.normalize(model.map_proto(v, u, h_sv), dim=-1)  # (|S|, d_z)
            proto_u_n = F.normalize(proto_u, dim=-1)                       # (K,   d_z)
            q_tilde = F.softmax(h_mapped @ proto_u_n.T / tau_d, dim=-1)   # (|S|, K)

            # Confidence weighting: max_k q̃ − 1/K
            with torch.no_grad():
                conf = (q_tilde.max(dim=1).values - 1.0 / n_clusters).clamp(min=0)

            kl = F.kl_div(
                (q_sv + EPS).log(),
                q_tilde.detach(),
                reduction="none",
            ).sum(dim=1)                                    # (|S|,)

            n_confident = int((conf > 0).sum().item())
            if n_confident > 0:
                total = total + (conf * kl).sum()
                count += n_confident

    if count == 0:
        return torch.zeros(1, device=H[0].device).squeeze()
    return delta * total / count
